### PR TITLE
Fixed Rollups that grab Hamburger menu

### PR DESCRIPTION
**Pull request by DHaussermann**
Fixed Rollups that grab Hamburger menu. span has been changed to a button causing these to fail

### CODE REVIEW

**Comment by DHaussermann** [comment]
@lindalu  There was a super quick fix to the user side hamburger menu.

**Comment by lindalumitchell** [comment]
Nice! And thanks! Will merge shortly.

**Comment by DylanH20** [comment]
Test Mention for @DHaussermann  
(testing that repository lock on github plugin is working as expected)

**Comment by DHaussermann** [comment]
Test mention 1 for @DylanH20

**Comment by DHaussermann** [comment]
Test mention 2 for @DylanH20

**Comment by DylanH20** [comment]
Mention 1 for @DHaussermann

**Comment by DylanH20** [comment]
Mention 2 for @DHaussermann

**Comment by DylanH20** [comment]
Mention 3 for @DHaussermann

**Pull request merged**
