### PR TITLE
Create SystmeConsoleGeneralPolicyIT.html

### PR DESCRIPTION
**Pull request by doh5**
Incldues General -> Policy -> Enable Team Invitation Setting Authority Test

### CODE REVIEW

**Comment by doh5** [comment]
@lindalumitchell 

Would you please review this PR and merge if looks good?

Thank you.

**Comment by lindalumitchell** [comment]
Thanks @doh5, looks pretty good! Just a couple comments/questions:

1. The HTML file title doesn't have to end with "IT" (just the javascript one). And looks like there's a typo as well (the m before the e), so maybe change the file name to be "SystemConsoleGeneralPolicy.html"?
2. In lines 104 and 109 (again in 741, 746), it looks like a dynamic ID of some sort is being used, so the test is breaking when it tries to find that target. (When I just tested it, for example, the IDs in the app reported as "id=manage-teams-iwt5g17zq7b47ckm5jxbionuno-toat6i96pffnzry7t4hxayp93w" instead of "id=manage-teams-yueo6xgbhpn7987x8g8qtne1th-afu531uwefgcdmjuixmyy8b9oh")

Everything else ran smoothly and worked well; looks really good.

**Comment by doh5** [comment]
@lindalumitchell 
Thanks for the review. I updated the name and the test:
-Removed the role change steps and used test2 account as the team admin.

Let me know if there's any other problem. Thanks.

**Comment by lindalumitchell** [comment]
@doh5 sorry for my delay in looking this over! It looks great, thanks for the updates.

**Pull request merged**
