### PR TITLE
dkh plugin maintenance

### PR DESCRIPTION
**Pull request by DHaussermann**
Maintenance work on Plugin test

### CODE REVIEW

**Comment by DHaussermann** [comment]
@lindalu I tried to put maintenance to the plugin test in a separate PR but it did not work. If you merge this PR https://github.com/mattermost/mattermost-selenium/pull/480 is no longer needed. 

Or safest would be to merge https://github.com/mattermost/mattermost-selenium/pull/480 and delete this one. I can create a separate PR for plugin maintenance later.

**Comment by lindalumitchell** [comment]
Ach, sorry @DHaussermann, I was going through messages in order and already merged #480 before reading this. So I guess this PR here can be deleted? I won't do anything else immediately. :)

Oh: the lindalu you mentioned above is linked to my personal Gmail account; sorry it's so confusingly close to my 'real' handle. I'll go look at changing that.

**Comment by DHaussermann** [comment]
Yes @lindalumitchell  please delete this PR. I can make a new PR later. I may be easiest if I just wait to get all your 5.16 maintenance locally and then I can create a new PR for this maintenance work. 

Sorry, I think I have always used the other GitHub handle for you :)

**Comment by lindalumitchell** [comment]
:) I hope I didn't seem to ignore past mentions from you! Completely unintentional, I promise. I don't really want to give up my personal `lindalu` handle (and someone else would probably grab it anyway, which would be even more confusing), but at the very least I've added my Mattermost avatar on my work handle. Not sure if that actually helps (if it shows up anywhere useful)....

I'll close this PR, sure. And I'll merge in my updates from last release at some point today.

**Pull request closed without merging**
