### PR TITLE
Update userextension-rollup.js  for Add to Team UI

### PR DESCRIPTION
**Pull request by DHaussermann**
Udated Rollup for Add to Team UI

### CODE REVIEW

**Comment by hanzei** [comment]
@DHaussermann Is this ready for review?

**Comment by DHaussermann** [comment]
Yes, @lindalu typically reviews open PRs for the Selenium Repo and merges them in.

**Comment by DHaussermann** [comment]
Added Permission updated to this same PR

**Comment by lindalumitchell** [comment]
LGTM!

**Pull request merged**
